case_codes = {
	"CF3": "AFTC",
	"ADM": "Admin Estate",
	"CAA": "Civil I",
	"CAB": "Civil II",
	"CAC": "Collections (Consent)",
	"CAD": "Collections (Denied)",
	"CCC": "Criminal Contempt",
	"CRT": "Criminal Tax",
	"DIS": "Disclaimer",
	"FDC": "Dist Crt Case",
	"CDC": "Dist Of Col",
	"DVM": "Domestic Violence",
	"CAE": "Eminent Domain",
	"FEL": "Felony",
	"CF1": "Felony I",
	"CF2": "Felony II",
	"CAF": "For. Jdgmt/Libel Of Info",
	"FEP": "Foreign Estate Proceeding",
	"FUG": "Fugitive",
	"CAH": "Housing Code Regulations",
	"CA1": "JIC 1",
	"CA2": "JIC 2",
	"CA3": "JIC 3",
	"SCJ": "Jury Demand (Small Claims)",
	"LTB": "Landlord &amp; Tenant Branch",
	"LIT": "Major Litigation",
	"CAM": "Malpractice",
	"CAP": "Merit Personnel Act",
	"CMD": "Misdemeanor",
	"CNC": "Non Criminal Cases",
	"CAO": "Other Administraive Reviews",
	"PAF": "Post &amp; Forfeit",
	"CAR": "Real Property",
	"SCB": "Small Claims Branch",
	"SEB": "Small Estate",
	"SC1": "Sml Clms &lt;=$500",
	"SC3": "Sml Clms &gt;$2,500 &lt;=$5,000",
	"SC2": "Sml Clms &gt;$500 &lt;=$2500",
	"CSP": "Spec Proc",
	"SPT": "Special Proceeding Tax",
	"CAS": "Structured Settlements",
	"CVT": "Tax Civil",
	"CAL": "Title 47",
	"CTF": "Traffic",
	"CAT": "Traffic Adj. Appeal",
	"CAV": "Vehicle - Automobile",
	"CRW": "Warrant",
	"WIL": "Will Filed",
}

party_codes = {
	"AC": "Amicus Curia",
	"ASSG": "Assignee",
	"ASSR": "Assignor",
	"AU": "Auditor",
	"CWT": "Complainant",
	"CIVCCD": "Counter Claim Defendant",
	"CR": "Creditor",
	"CIVXD": "Cross Defendant",
	"CIVXP": "Cross Plaintiff",
	"DCDNT": "Decedent",
	"DFNDT": "Defendant",
	"CDEF": "Defendant (Criminal)",
	"CIVCP": "Defendant Counter Plaintiff",
	"DEVISEE": "Devisee",
	"DISCLMT": "Disclaimant",
	"DON": "Donor",
	"FPAYOR": "Fine PAYER",
	"CIVFPD": "Fourth Party Defendant",
	"FPD": "Fourth Party Defendant",
	"FPP": "Fourth Party Plaintiff",
	"GN": "Garnishee",
	"HR": "Heir",
	"INTERV": "Intervenor",
	"MPY": "Miscellaneous Party",
	"NN": "New Name",
	"PR": "Personal Representative",
	"PET": "Petitioner",
	"PLNTF": "Plaintiff",
	"PLTFTNT": "Plaintiff / Tenant",
	"CIVCD": "Plaintiff Counter Defendant",
	"PROHV": "Pro Hac Vice",
	"PRO SE": "Pro Se",
	"RE": "Receiver",
	"RSPND": "Respondent",
	"SUBROGEE": "SUBROGEE",
	"SQLOT": "Square/Lot",
	"TRUSTEE": "TRUSTEE",
	"THIRDPTYP": "Third Party",
	"THIRDPTYD": "Third Party - Defendant",
	"CIVTPD": "Third Party Defendant",
	"TRSBEN": "Trust Beneficiary",
	"UNKH": "Unknown Heirs",
}

status_codes = {
	"APP": "Appeal",
	"A": "Appeal -Crm",
	"AP": "Approved",
	"BWA": "Bench Warrant",
	"C": "Closed",
	"O": "Open",
	"RO": "Reopen (RO)",
}
